apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: content-library-dev


patchesStrategicMerge:
- ./serviceaccount.yaml
- ./ingress.yaml
- ./deployment.yaml
resources:
- ../../base
images:
- name: gcr.io/adhoc-dev-service-platform/content-library
  newTag: a827f78cd34a9915733966cdac10b487f8efefe3
