# gcloud datastore indexes create ./index.yaml --project your-gcp-project-here

indexes:
- kind: LibraryViewDoc
  properties:
  - name: userId
  - name: viewCount
    direction: desc
- kind: LibraryViewDoc
  properties:
  - name: userId
  - name: lastViewedAt
    direction: desc
- kind: LibraryViewTeam
  properties:
  - name: userId
  - name: viewCount
    direction: desc
- kind: LibraryViewTeam
  properties:
  - name: userId
  - name: lastViewedAt
    direction: desc