name: Build and push content library image to GCR
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v0.8.3'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.ADHOC_GCR_PLATFORM_DEV_WORKLOAD_IDENTITY_ID }}'
          service_account: '${{ secrets.ADHOC_GCR_PLATFORM_DEV_WORKLOAD_IDENTITY_EMAIL }}'

      - name: Setup cloud SDK with Dev project info
        uses: 'google-github-actions/setup-gcloud@v0.6.0'
        with:
          project_id: '${{ secrets.ADHOC_GCR_PLATFORM_DEV_PROJECT_ID }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # This example uses the docker login action
      - name: Log into GCR registry
        uses: 'docker/login-action@v2'
        with:
          registry: 'gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and push image to GCR
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          push: true
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
          tags: gcr.io/${{ secrets.ADHOC_GCR_PLATFORM_DEV_PROJECT_ID }}/content-library:${{ env.TAG }},gcr.io/${{ secrets.ADHOC_GCR_PLATFORM_DEV_PROJECT_ID }}/content-library:latest
