name: Build and push content library image to GCR
on:
  push:
    branches:
      - main
jobs:
  build-push-image:
    if: github.actor != 'jenkins-adhoc-team'
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.ADHOC_GCR_PLATFORM_DEV_WORKLOAD_IDENTITY_ID }}'
          service_account: '${{ secrets.ADHOC_GCR_PLATFORM_DEV_WORKLOAD_IDENTITY_EMAIL }}'

      - name: Setup cloud SDK with Dev project info
        uses: 'google-github-actions/setup-gcloud@v1.0.1'
        with:
          project_id: '${{ secrets.ADHOC_GCR_PLATFORM_DEV_PROJECT_ID }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # This example uses the docker login action
      - name: Log into GCR registry
        uses: 'docker/login-action@v2'
        with:
          registry: 'gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and push image to GCR
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          push: true
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
          tags: gcr.io/${{ secrets.ADHOC_GCR_PLATFORM_DEV_PROJECT_ID }}/content-library:${{ env.TAG }},gcr.io/${{ secrets.ADHOC_GCR_PLATFORM_DEV_PROJECT_ID }}/content-library:latest

  deploy:
    permissions:
      contents: 'write'
      id-token: 'write'
      repository-projects: 'write'
    strategy:
      max-parallel: 1
      matrix:
        environment: [dev, prod]
    needs:
      - build-push-image
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - name: Checking Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@6691bdeb1b0a3286fb7f70fd1423c10e81e5375f
      - name: Set dev image version to new commit SHA
        run: cd ops/platform-dev/overlays/${{ matrix.environment }} && kustomize edit set image gcr.io/${{ secrets.ADHOC_GCR_PLATFORM_DEV_PROJECT_ID }}/content-library:${{ env.TAG }}
      
      # The PAT method is a hacky workaround that gets around the limitation that the GHA token is not able to bypass the main branch
      # protection rule.
      # https://github.com/community/community/discussions/13836
      - name: Push kustomize edit into Github
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ADHOC_GH_UTILITY_ACCESS_TOKEN }}
        run: |
          git config user.email "infrastructure@adhocteam.us"
          git config user.name "Ad Hoc Infrastructure Bot"
          git config --global url.https://$GITHUB_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          git commit -am "GitOps: Update ${{ matrix.environment }} deployment image to ${{ env.TAG }}"
          git pull --rebase
          git push
